### ISSUE TITLE
DataStorage classes need to be set up

### ISSUE THREAD

**Issue by anthonymesa** [anthonymesa/Cwacos#11]
The three data storage classes that we need will be the DataStorage class itself, a StorageAdapter interface, and a LocalStorageTranslator (the starting files for this have been posted to the groupchat)

**Comment by Alan-Choi** [comment]
The Store method in the LocalStorageTranslator Class. What are the two array lists (params, and input) supposed to be? if params is the path of the file and the input is the actual data to be stored, is there a reason why params has to be an array list?

**Comment by anthonymesa** [comment]
They should take these parameters as arraylists because LocalFileStorage implements the Storage Adapter interface so that the LocalFileStorage class can be initialized as StorageAdapter type in the DataStorage class.

You are right, in this instance uaing local file storage it is very posible there is only one parameter to be used by this local file storage translator, but what if we find out we need to use a database instead of local file storage?

A DatabaseTranslator class would also implement the Storage Adapter interface above which takes the same arraylist parameters for the same reason as above, bbut a database may actually require more parameters: maybe url, port, server instance id, table id, etc. In that case, we have to rewrite no new code except for the DatabaseTranslator given that the StorageAdapter arraylist paramters allow for a single parameter or multiple.

It is for modularity of code really.

**Comment by Alan-Choi** [comment]
I understand that the purpose of the classes are for code modularity, but I don't understand what the parameters of the methods in LocalStorageTranslator Class. is Arraylist<String> params an array list with one element that contains the path of the file and ArrayList<String> input the data to be written or overwritten to the file?

**Comment by anthonymesa** [comment]
Thats exactly it, yes, the params would hpld the local file url and the input is the data that needs to be saved, sorry for the confusion!

**Comment by Alan-Choi** [comment]
When we store the entry, are we storing one entry? In other words, is the entry the same as the params, an Array List containing one element?

**Comment by anthonymesa** [comment]
No, it holds many entries. lets say that the markets open at 8:00am, and at 8:30am we make an API request for intraday market data, saying we want the data in 5-minute intervals. Michael's API code will then retrieve that data and save it as an arraylist of 6 Entry objects, because there were 6 5-minute intervals from 8:00am to 8:30am.

I figure the best way to do it is to just save those Entry objects in the input arraylist one per line.

Yall can agree on how yall want to parse it

**Comment by aDjido** [comment]
so all entries must be stored in the array right?but i thought the only
data being stored is what the user saves or is it just simply every 5
minute interval being stored?

**Comment by anthonymesa** [comment]
Michaels api call stores the data retrieved by the api as an arraylist of Entry objects (via the Entry class). Each entry object represents a single time interval in the day, so if an intraday call is made with the "5min" parameter, then each Entry object will have the buying and selling high and low for every 5min interval of the day thus far. If the parameter is "10min" then it will be the same, but each Entry object now has that same data but for every 10min interval of the day thus far.

So yes, the only data being stored is the 5min (or 10min, 30min, etc.) interval data that the user has generated and now wants to save.

For example:

1. User wants to see GME intraday stock data.
2. User clicks dropdown menu and selects GME.
3. Data table UI window for favorited GME stock is currently empty
4. User clicks "update" to generate intraday GME stock data (lets use the example above and say since the call was made at 8:30 an arraylist is returned that is 6 entries long - this is the relevant stock intraday data).
5. That inraday stock data is displayed in the UI table for the user to see.
6. The user can then click the save button, which takes that stock data ArrayList of Entry objects being displayed to the table, and sends it as a parameter to the Store function, storing the current data that the user has just generated and is seeing in the UI.

Now, lets say that two days pass and the user opens the program fresh, so all of tables for their favorite stocks are empty (because the user hasnt yet clicked the "update" button on a single ticker, or the "update all" button). Lets also say that the user wants to load back into the UI table that same data that they viewed two days ago that they saved in step 6. The user clicks "Load", provides a file url, and then the program reads the file that was saved in step 6 for the GME ticker. Now, when the user selects GME in the stocks dropdown list, they see the data that was downloaded in step 4 displayed in the UI table like it was in step 5.

I hope this helps

**Comment by anthonymesa** [comment]
Also, I forgot to mention - because the save function's input parameter is an arraylist of strings, in the DataStorage class you will want to convert the ArrayList of Entry's proved to the save function in DataStorage class into an ArrayList of strings before calling the save method in the file translator. Easiest way to do this may be for me to update the toString method that Michel is using in the Entry class he wrote. That way the Entry.toString() method would return a string of comma seperated key-value pairs all together in one string.
