### ISSUE TITLE
After removing a stock/crypto, activeData should be set to next available ticker and table/graph need populated

### ISSUE THREAD

**Issue by anthonymesa** [anthonymesa/Cwacos#49]

**Comment by Alan-Choi** [comment]
How are we keeping track of which ticker is active? I see generateActiveDataTableComponent method, but I don't see that in the gui when the program is running.

**Comment by anthonymesa** [comment]
yes you are correct. the variable activeSymbol in the CwacosData class is the current symbol being viewed. It has its own getters and setters.
