### ISSUE TITLE
Improper file saving on exit

### ISSUE THREAD

**Issue by anthonymesa** [anthonymesa/Cwacos#58]
An exception is thrown while saving state on close due to line 200 in CwacosData in the saveData function. getFileUrl returns null if a file url has not been generated already (which now only happens after a user has created one using the save dialogue). In this case, maybe a default url and file location can be used?

**Comment by Alan-Choi** [comment]
When exactly is this exception thrown?

**Comment by Alan-Choi** [comment]
This has been addressed by pull request #68, but I'm not a 100% sure if it handled in completely, or just bypassed the issue.
